### ISSUE TITLE
Automate the API keys and some other stuff with the arr tools

### ISSUE THREAD

**Issue by ullbergm** [ullbergm/openshift#41]
- [ ] sabnzbd
```
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.downloads,
                sabnzbd.downloads.svc,
                sabnzbd.downloads.svc.cluster,
                sabnzbd.downloads.svc.cluster.local,
                sabnzbd.bjw-s.dev
              SABNZBD__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: api_key
              SABNZBD__NZB_KEY:
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: nzb_key
```

- [ ] sonarr
```
              COMPlus_EnableDiagnostics: "0"
              SONARR__APP__INSTANCENAME: Sonarr
              SONARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: sonarr-secret
                    key: api_key
              SONARR__AUTH__METHOD: External
              SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
              SONARR__LOG__LEVEL: info
              SONARR__SERVER__PORT: &port 8989
```
- [ ] radarr
```
              COMPlus_EnableDiagnostics: "0"
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 7878
              RADARR__AUTHENTICATION_METHOD: External
              RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              RADARR__APPLICATION_URL: "https://radarr.bjw-s.dev"
              RADARR__LOG_LEVEL: info
              RADARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: radarr-secret
                    key: api_key
```
- [ ] prowlarr
```
              COMPlus_EnableDiagnostics: "0"
              PROWLARR__INSTANCE_NAME: Prowlarr
              PROWLARR__PORT: &port 9696
              PROWLARR__LOG_LEVEL: info
              PROWLARR__ANALYTICS_ENABLED: "False"
              PROWLARR__AUTHENTICATION_METHOD: External
              PROWLARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: prowlarr-secret
                    key: api_key
```
